# Secrets Configuration
# Copyright (C) 2018 Carl Araya
# This is a course requirement for CS 192 Software Engineering II under the supervision of Asst. Prof. Ma. Rowena C. Solamo of the Department of Computer Science, College of Engineering, University of the Philippines, Diliman for the AY 2015-2016
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# You should have received a copy of the GNU General Public License
# along with this program. If not, see https://www.gnu.org/licenses/.
# **CHANGELOG**
# Carl Araya 2/07/18 - Initial creation
# 
# File created on: 2/07/18
# Developer: Carl Araya
# Client: UP Diliman Department of Computer Science Student Organizations
# This software aims to provide a convenient avenue for student organizations to display their org and collect contact information from students interested in joining them.

development:
  secret_key_base: afdfa4c0918e60628def1b6e42743d153f0d3998a92a88056adbff3836c0b798575837d398b7106187bed2db7b130b9ad99476e99bb23a15177ee62324e16323

test:
  secret_key_base: 1d00facdd44e8b4d46a069b209aa80b558b1e6f48e1ea4dd9a063d2d70d9c1cfdff25655e92e8ffc1d8651f5df88e74da798f92322fcd162e2a33b03ec2eaae2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
