local:
  service: Disk
  root: <%= Rails.root.join("storage") %>
 
google:
  service: GCS
  credentials: <%= Rails.root.join("config/keyfile.json") %>
  project: "what-is-this@possible-sun-157211.iam.gserviceaccount.com"
  bucket: "coupon-upd"
